version: "2"
linters:
  default: standard
  enable:
    - gosec
    - bodyclose
  exclusions:
    rules:
      - linters: [gosec]
        text: "G101:"
      - linters: [gosec]
        path: _test\.go
      - linters: [gosec]
        path: internal/totp/totp\.go
        text: "G505:"
      - linters: [gosec]
        path: internal/totp/totp\.go
        text: "G115:"
