export const P = {
  dashboard: "dashboard:read",
  userList: "user:list",
  userDetail: "user:detail",
  userCreate: "user:create",
  userUpdate: "user:update",
  userDelete: "user:delete",
  userRoles: "user:roles",
  userAvatar: "user:avatar",
  userExport: "user:export",
  userImport: "user:import",
  userRevoke: "user:revoke",
  userSessions: "user:sessions",
  userSessionRevoke: "user:session:revoke",
  userReset: "user:reset",
  userUnlock: "user:unlock",
  userBatch: "user:batch",
  roleList: "role:list",
  roleDetail: "role:detail",
  roleCreate: "role:create",
  roleUpdate: "role:update",
  roleDelete: "role:delete",
  rolePerms: "role:perms",
  roleCopy: "role:copy",
  permList: "perm:list",
  permCreate: "perm:create",
  permUpdate: "perm:update",
  permDelete: "perm:delete",
  dictList: "dict:list",
  dictCreate: "dict:create",
  dictUpdate: "dict:update",
  dictDelete: "dict:delete",
  dictItemCreate: "dict:item:create",
  dictItemUpdate: "dict:item:update",
  dictItemDelete: "dict:item:delete",
  configList: "config:list",
  configCreate: "config:create",
  configUpdate: "config:update",
  configBatch: "config:batch",
  configDelete: "config:delete",
  mailTest: "mail:test",
  mailJobsList: "mail:jobs:list",
  mailJobsRetry: "mail:jobs:retry",
  mailJobsCancel: "mail:jobs:cancel",
  mailCampaignList: "mail:campaign:list",
  mailCampaignDetail: "mail:campaign:detail",
  mailCampaignCreate: "mail:campaign:create",
  mailCampaignUpdate: "mail:campaign:update",
  mailCampaignDelete: "mail:campaign:delete",
  mailCampaignSchedule: "mail:campaign:schedule",
  logList: "log:list",
  logClear: "log:clear",
  logPurge: "log:purge",
  logExport: "log:export",
  deptList: "dept:list",
  deptCreate: "dept:create",
  deptUpdate: "dept:update",
  deptDelete: "dept:delete",
  menuList: "menu:list",
  menuCreate: "menu:create",
  menuUpdate: "menu:update",
  menuDelete: "menu:delete",
  notifyList: "notify:list",
  announceCreate: "announce:create",
  sessionList: "session:list",
} as const

export type PermCode = (typeof P)[keyof typeof P]

export const KIND_LABEL: Record<string, string> = {
  menu: "菜单",
  button: "按钮",
  api: "接口",
}
